version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doctorsalon
    volumes:
      - db-data:/var/lib/postgresql/data
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/doctorsalon
    depends_on:
      - db
volumes:
  db-data:
